sudo: required
services:
  - docker
before_install:
  - docker build -t thanhntdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thanhntdocker/react-test npm run test

after_success:
  - docker build -t thanhntdocker/multi-client ./client
  - docker build -t thanhntdocker/multi-nginx ./nginx
  - docker build -t thanhntdocker/multi-server ./server
  - docker build -t thanhntdocker/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push thanhntdocker/multi-client
  - docker push thanhntdocker/multi-nginx
  - docker push thanhntdocker/multi-server
  - docker push thanhntdocker/multi-worker